import { useState, type ReactNode } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, ArrowUpRight, BookOpen, Boxes, Check, ChevronDown, ChevronRight, CircleHelp, Compass, FileCheck2, Image, MapPin, Menu, Network, PenLine, Route, UsersRound, X } from 'lucide-react'
import type { MagazineData, Workspace } from '../lib/types'
import { BrandMark } from './ui'

const workspaceLabels: Record<Workspace, string> = { explore: 'Explorer la France', coffrets: 'Les 365 coffrets', tours: 'Les tournées', editor: 'Éditeur intérieur', media: 'Médiathèque', places: 'Lieux & territoires', professionals: 'Les professionnels' }
export default function Shell({ children, workspace, onNavigate, onClaim, onAbout, onExport, onImport, data, saveState }: { children: ReactNode; workspace: Workspace; onNavigate: (w: Workspace) => void; onClaim: () => void; onAbout: () => void; onExport: () => void; onImport: () => void; data: MagazineData; saveState: string }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const nav = (w: Workspace) => { onNavigate(w); setMobileOpen(false) }
  const navItem = (w: Workspace, Icon: typeof Compass, extra?: ReactNode) => <button className={`side-nav-item ${workspace === w ? 'active' : ''}`} onClick={() => nav(w)}><Icon size={17} strokeWidth={1.6}/><span>{workspaceLabels[w]}</span>{extra}</button>
  return <div className="app-shell">
    {mobileOpen && <div className="sidebar-scrim" onClick={() => setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
      <button className="brand" onClick={() => nav('explore')} aria-label="World Wedding Magazine, accueil"><BrandMark/><div className="brand-name">WORLD WEDDING<span>MAGAZINE</span></div><div className="brand-edition"><i/> ÉDITION FRANCE <i/></div></button>
      <button className="mobile-close icon-button" onClick={() => setMobileOpen(false)} aria-label="Fermer le menu"><X size={18}/></button>
      <nav className="side-nav" aria-label="Navigation principale"><div className="nav-label">LE MAGAZINE</div>{navItem('explore', Compass)}{navItem('coffrets', Boxes, <span className="nav-count">365</span>)}{navItem('tours', Route, <span className="nav-new">NOUVEAU</span>)}<div className="nav-divider"/><div className="nav-label">L’ATELIER ÉDITORIAL</div>{navItem('editor', PenLine, <ArrowUpRight className="nav-arrow" size={13}/>)}{navItem('media', Image)}<div className="nav-divider"/><div className="nav-label">LES LIENS DU MAGAZINE</div>{navItem('places', MapPin)}{navItem('professionals', UsersRound)}</nav>
      <div className="sidebar-bottom"><div className="contribute-card"><div className="contribute-illustration"><BookOpen size={25} strokeWidth={1}/><span>✧</span></div><h3>Une belle histoire<br/>commence avec vous.</h3><p>Un lieu, un savoir-faire, une journée.<br/>Faites partie du magazine.</p><button onClick={onClaim}>Revendiquer un coffret<ArrowUpRight size={14}/></button></div><button className="living-status" onClick={onAbout}><span className="live-dot"/><span>Un magazine vivant<small>Une source. Mille façons de raconter.</small></span><ChevronRight size={13}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb-main"><button className="mobile-menu icon-button" aria-label="Ouvrir le menu" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><BookOpen size={16} strokeWidth={1.5}/><button onClick={() => nav('explore')}>Le magazine</button><ChevronRight size={12}/><span>{workspaceLabels[workspace]}</span></div><div className="topbar-right"><span className="edition-indicator"><i className="french-flag"/> FRANCE <span>·</span> 2026</span><div className="topbar-separator"/><button className="icon-button help-button" onClick={onAbout} aria-label="À propos du magazine"><CircleHelp size={18} strokeWidth={1.5}/></button><div className="profile-wrap"><button className="profile-button" onClick={() => setProfileOpen(!profileOpen)} aria-label="Ouvrir le menu de l’atelier" aria-expanded={profileOpen}><span>É</span><ChevronDown size={12}/></button>{profileOpen && <><div className="dropdown-dismiss" onClick={() => setProfileOpen(false)}/><div className="profile-menu"><div className="profile-menu-heading"><strong>Votre atelier</strong><span><span className={`live-dot ${saveState === 'error' ? 'error' : ''}`}/>{saveState === 'saved' ? 'Enregistré sur cet appareil' : saveState === 'error' ? 'Sauvegarde indisponible' : 'Enregistrement…'}</span></div><button onClick={() => { onExport(); setProfileOpen(false) }}><ArrowDownToLine size={15}/>Exporter le magazine</button><button onClick={() => { onImport(); setProfileOpen(false) }}><ArrowUpFromLine size={15}/>Importer une sauvegarde</button><button onClick={() => { onAbout(); setProfileOpen(false) }}><FileCheck2 size={15}/>Audit & architecture</button><div className="profile-menu-note"><Check size={13}/> {data.coffrets.length} coffrets, une source commune.</div></div></>}</div></div></header><main className={`main-content ${workspace === 'editor' ? 'editor-content' : ''}`}>{children}</main><footer className="main-footer"><span>WORLD WEDDING MAGAZINE <i>—</i> FRANCE</span><p>365 coffrets. 24 moments. Un seul magazine.</p><button onClick={onAbout}>La philosophie du projet <Network size={13}/></button></footer></div>
  </div>
}
